### ISSUE TITLE
No message in notification

### ISSUE THREAD

**Issue by Somora** [torgrimt/zabbix-ntfy#17]
Good evening!

I'm trying setting up NTFY in Zabbix. Everything seems to be working but when i sent a test like this:

![Image](https://github.com/user-attachments/assets/e39c471e-5d02-45be-9575-c38b7c7b960b)

The message will not appear:

![Image](https://github.com/user-attachments/assets/bcfebb78-d411-4071-b3c0-04e2059dba8f)

It also does this wit ha real alert.

Any idea how i can fix this?

Thanks in advance!

**Comment by Chrispeerboom** [comment]
Hello i ve the same problem, do you find a solution ? 

Tx

**Comment by TENTE-Dotterer** [comment]
Hello everyone,
i have had the same issue and boiled it down to the ntfy server beeing misconfigured. Im not sure what exact setting solved it for me but after adding
```yaml
auth-file: "/var/lib/ntfy/auth.db"
cache-file: "/var/cache/ntfy/cache.db"
upstream-base-url: "https://ntfy-sh"
auth-default-access: "deny-all"
tz: "UTC"
```
to the `/etc/ntfy/server.yml` and restarting the ntfy service, creating a user with admin rights, getting a token and setting up zabbix to use the token, the message template appeared.

The strangest thing is that the message content would be sent if testing manually. It seems to be something with how the template is formatted that ntfy does not like out of the box.
